//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prode.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuentro
    {
        public int Id { get; set; }
        public int IdLocal { get; set; }
        public int IdVisitante { get; set; }
        public int Fecha { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
    }
}
